# Generated by Django 2.2.5 on 2019-09-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='last_name',
        ),
    ]
